Push the complete apple-clone-website to master
harshdeepkanhai/apple-website-clone pull request #1
Opened 2020-07-06 15:14 UTC by harshdeepkanhai

2020-07-06 20:12 UTC, addod19 commented
## Pull Request under review by Daniel Larbi Addo (TSE)

2020-07-06 20:27 UTC, addod19 requested changes
## Status: Require changes :recycle: :traffic_light: 

Hi @harshdeepkanhai, great job on this amazing project :+1: README is professional, Commit messages descriptive and the project looks great. However, we can improve our project and get our project approved by addressing the comments below: :slightly_smiling_face:
- We currently have a huge space at the footer, let us fix it
![xtra](https://user-images.githubusercontent.com/46388113/86638165-580e8d80-bfc6-11ea-9bcb-84c930273e4d.png)
- Let us fix the margin between the hero image and the four buttons
![mar](https://user-images.githubusercontent.com/46388113/86637874-db7baf00-bfc5-11ea-869d-8afd1cbd79e2.png)
- Let us add a link to the copyright as required
![mar1](https://user-images.githubusercontent.com/46388113/86637970-00702200-bfc6-11ea-85c4-d7c590cb344b.png)
- There are some repeating codes in our CSS file, let us apply the DRY rule
- The HTML validator returned 1 warning which is easily fixable

Kindly fix these comments and submit another code review :smile: 
_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

2020-07-07 00:06 UTC, andresporras3423 requested changes
### Status: Changes Required :recycle:
**Hello @harshdeepkanhai** 
Good job with your new submission for this project :muscle:  
Your project passes most of the requirements.  :clap: :clap: :clap:  
There are just a few details to improve before you can go ahead:
- [x] Don't repeat yourself, in order to minimize code you can group selectors with the same style definition, or you can create a new class.
- [x]  Check the footer of your page, it looks like this on my screen (1321px wide):

![](http://imgur.com/CrUkd8Ll.png)

Please request another review once you are ready! :+1: 

Happy coding :relaxed:

Oscar Andrés Russi Porras

2020-07-07 00:06 UTC, andresporras3423 commented on assets/stylesheets/main.css
> +}
group selectors:
```suggestion
.flex, .flex-2 {
  display: flex;
  align-items: center;
}
```
or create a new class:
```suggestion
.new_class_name {
  display: flex;
  align-items: center;
}
```

2020-07-07 01:22 UTC, voscarmv requested changes
# Nice work so far @harshdeepkanhai 👍 
## However, there are some changes required 👀 🧰 🔨 🔧 

- On my screen, the navbar is not centered, and the footer text is misplaced:

![image](https://user-images.githubusercontent.com/2739245/86681876-9d7e8b00-bfc5-11ea-8376-0ca7b024bfb9.png)

![image](https://user-images.githubusercontent.com/2739245/86681904-a5d6c600-bfc5-11ea-8eae-c0c4bfcba89e.png)

Your page is supposed to look good for all screen sizes. To test this, you may change the zoom % on your browser, to check that the positioning does not become scrambled when you change the screen size.

You may use relative width units like `vw` or `%` to make your page layout more [fluid](https://alistapart.com/article/fluidgrids/).

### Submit these changes and request a new code review! 😄 👍 
### Questions or comments? Reach me on [Twitter](https://twitter.com/voscarmv) or [LinkedIn](https://linkedin.com/in/oscar-mier) 🧑‍💻🗨️🧑‍💻 
# Happy Hacking! 🧠 ⌨️ 🖱️ 🖥️

2020-07-07 13:19 UTC, bertil291utn commented
# Status: on review 🟠 

##### *Reach out to me on* [Twitter](bit.ly/bertil-twitter) , [LinkedIn](bit.ly/bertil_linkedin) or Slack Microverse-community as @btandayamo

2020-07-07 13:46 UTC, bertil291utn commented
# Project Approved ✔️ 

Hi, @harshdeepkanhai  your project was approved, please merge to master branch and move on with the next assignments.
You're doing  a great job keep going 💻 🚀 🔥


[OPTIONAL]
In order to approach a better project which looks like exactly clon as the actual apple web page 
- Be careful with the typos 
- Responsiveness page
   Add a min-width property inside the body attribute and try to use % or instead of px

##### *Reach out to me on* [Twitter](bit.ly/bertil-twitter), [LinkedIn](bit.ly/bertil_linkedin) or Slack Microverse-community like @btandayamo

2020-07-07 13:59 UTC, merged